### Carrega dependencias e diretório bronze

In [29]:
import json
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from IPython.display import display
import pyarrow as pa

#getenv puxa a variável do ambiente
load_dotenv()
BRONZE_POKEMON = f"{os.getenv('BRONZE')}\\pokemon"
BRONZE_POKEMON_SPECIES = f"{os.getenv('BRONZE')}\\pokemon-species"
BRONZE_ENCOUNTERS = f"{os.getenv('BRONZE')}\\encounters"
BRONZE_EVOLUTION_CHAIN = f"{os.getenv('BRONZE')}\\evolution-chain"
BRONZE_TYPES = f"{os.getenv('BRONZE')}\\type"
SILVER_INTERMEDIARIA = f"{os.getenv('SILVER')}\\silver-intermediaria"

### Configura mysql

In [30]:
USER = os.getenv("USER")
PASSWORD = os.getenv("PASSWORD")
HOST = os.getenv("HOST")
PORT = os.getenv("PORT")
DATABASE = os.getenv("DATABASE")

# 2. Build the connection string (URL)
# Format: mysql+driver://user:password@host:port/database
connection_string = f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"

# 3. Create the SQLAlchemy engine
# pool_pre_ping=True checks if the connection is alive before using it
engine = create_engine(
    connection_string,
    pool_pre_ping=True,
    echo=True,  # Set to True to see the generated SQL queries in your console
)

### Função para carregar json

In [31]:
def load_json (directory, file):
    if not os.path.exists(f"{directory}\\{file}"):
        print(f"File not found: {file}")
        return None

    with open(f"{directory}\\{file}", "r", encoding="utf-8") as f:
        data = json.load(f)

    return data

### tratamento pokemon_species

#### v2

In [32]:
# os.listdir trás o nome dos arquivos do diretório em formato de lista
pokemon_species_list = []

for file_name in os.listdir(BRONZE_POKEMON_SPECIES):

    if not file_name.endswith('.json'):
        continue
    # existe uma maneira mais limpa já que todos vão ter try/except pelas mesmas razões?
    try:
        df_raw = pd.json_normalize(load_json(BRONZE_POKEMON_SPECIES, file_name)) #já entrega um df
        evo_id = df_raw['evolution_chain.url'].str.split('/').str[-2]
        pokemon_species_cols = df_raw[['id', 'name', 'habitat.name', 'is_baby', 'is_legendary','is_mythical']]

        df_species = pd.concat([pokemon_species_cols, evo_id], axis=1)
        df_species = df_species.rename(columns={'evolution_chain.url': 'evolution_chain_id', 'habitat.name': 'habitat'})

        pokemon_species_list.append(df_species)
    except Exception as e:
        print(f"Failed on file {file_name}: {e}")
        continue

df_pokemon_species = pd.concat(pokemon_species_list).set_index("id").sort_values(by="id").drop_duplicates()
display(df_pokemon_species)

,name,habitat,is_baby,is_legendary,is_mythical,evolution_chain_id
id,,,,,,
1,bulbasaur,grassland,False,False,False,1
2,ivysaur,grassland,False,False,False,1
3,venusaur,grassland,False,False,False,1
4,charmander,mountain,False,False,False,2
5,charmeleon,mountain,False,False,False,2
...,...,...,...,...,...,...
147,dratini,waters-edge,False,False,False,76
148,dragonair,waters-edge,False,False,False,76
149,dragonite,waters-edge,False,False,False,76
150,mewtwo,rare,False,True,False,77
151,mew,rare,False,False,True,78

#### v1

In [33]:
# # os.listdir trás o nome dos arquivos do diretório em formato de lista
# pokemon_species_list = []

# for i in os.listdir(BRONZE_POKEMON_SPECIES):
#     # existe uma maneira mais limpa já que todos vão ter try/except pelas mesmas razões?

#     try:
#         data = pd.json_normalize(load_json(BRONZE_POKEMON_SPECIES, i))
#         pokemon_species_fields = {

#             "id": data["id"],
#             "name": data["name"],
#             "evolution_chain_id": data["evolution_chain"]["url"].split("/")[-2],
#             "habitat": data["habitat"]["name"] if data["habitat"] else None,
#             "is_baby": data["is_baby"],
#             "is_legendary": data["is_legendary"],
#             "is_mythical": data["is_mythical"],
#         }
#         pokemon_species_list.append(pokemon_species_fields)
#     except Exception as e:
#         print(f"Failed on file {i}: {e}")
#         continue

#     df_pokemon_species = pd.DataFrame(pokemon_species_list)
#     tb_pokemon_species = df_pokemon_species.set_index("id").sort_values(by="id").drop_duplicates()

#     print(tb_pokemon_species)

In [34]:
# v1
# pokemon_species_list = []

# for i in os.listdir(BRONZE_POKEMON_SPECIES):
#     with open(
#         f"{BRONZE_POKEMON_SPECIES}\\{i}",
#         "r",
#         encoding="utf-8",
#     ) as f:
#         data = json.load(f)

#     pokemon_species_fields = {
#         "id": data["id"],
#         "name": data["name"],
#         "evolution_chain_id": data["evolution_chain"]["url"].split("/")[-2],
#         "habitat": data["habitat"]["name"],
#         "is_baby": data["is_baby"],
#         "is_legendary": data["is_legendary"],
#         "is_mythical": data["is_mythical"],
#     }

#     pokemon_species_list.append(pokemon_species_fields)

# df_pokemon_species = pd.DataFrame(pokemon_species_list)
# tb_pokemon_species = df_pokemon_species.set_index("id").sort_values(by="id").drop_duplicates()

# print(tb_pokemon_species)


### tratamento location_encounters

#### v2

In [35]:
# os.listdir trás o nome dos arquivos do diretório em formato de lista

location_area_list = []

for file_name in os.listdir(BRONZE_ENCOUNTERS):

    file = load_json(BRONZE_ENCOUNTERS, file_name)

    if not file_name.endswith('.json'):
        continue

    if file == []:
        print(f'Skipping file {file_name}. No encounter locations available.')
        continue

    try:
        df_raw = pd.json_normalize(file)

        location_id = df_raw['location_area.url'].str.split('/').str[-2]
        location_name = df_raw[['location_area.name']]

        df_location = pd.concat([location_id, location_name], axis=1)
        df_location["pokemon_id"] = file_name.split("_")[0]
        df_location = df_location.rename(columns={'location_area.url': 'id', 'location_area.name': 'name'})

        location_area_list.append(df_location)

    except Exception as e:
        print(f"Failed on file {file_name}: {e}")
        continue

df_encounters = pd.concat(location_area_list).set_index("id").sort_values(by="id").drop_duplicates()
display(df_encounters)

Skipping file 134_vaporeon.json. No encounter locations available.
Skipping file 135_jolteon.json. No encounter locations available.
Skipping file 136_flareon.json. No encounter locations available.
Skipping file 139_omastar.json. No encounter locations available.
Skipping file 141_kabutops.json. No encounter locations available.
Skipping file 3_venusaur.json. No encounter locations available.
Skipping file 68_machamp.json. No encounter locations available.
Skipping file 9_blastoise.json. No encounter locations available.

                  name pokemon_id
id
1   canalave-city-area        120
1   canalave-city-area        129
1   canalave-city-area         73
1   canalave-city-area        130
1   canalave-city-area         72
..                 ...        ...
9   eterna-forest-area         11
9   eterna-forest-area         14
9   eterna-forest-area         92
9   eterna-forest-area         13
9   eterna-forest-area         10

[4066 rows x 2 columns]

#### v1

In [36]:
# # os.listdir trás o nome dos arquivos do diretório em formato de lista

# location_area_list = []

# for i in os.listdir(BRONZE_ENCOUNTERS):

#     try:
#         data = load_json(BRONZE_ENCOUNTERS, i)

#         for location in data:
#             location_area = location["location_area"]

#             encounters_fields = {

#                     "id": location_area["url"].split("/")[-2],
#                     "name": location_area["name"],
#                     "pokemon_id": i.split("_")[0]
#             }

#             location_area_list.append(encounters_fields)

#     except Exception as e:
#         print(f"Failed on file {i}: {e}")
#         continue

# df_encounters = pd.DataFrame(location_area_list)
# tb_encounters = df_encounters.set_index("id").sort_values(by="id").drop_duplicates()
# print(tb_encounters)

### tratamento evolution_chain

In [37]:
# os.listdir trás o nome dos arquivos do diretório em formato de lista

evolution_chain_list = []

for i in os.listdir(BRONZE_EVOLUTION_CHAIN):

    try:
        data = load_json(BRONZE_EVOLUTION_CHAIN, i)

        if not data["chain"]["evolves_to"]:
            continue

        base_species = data["chain"]["species"] # base da evolution_chain
        evolution_items = data["chain"]["evolves_to"]

        for evolution in evolution_items:
            evolution_details = evolution["evolution_details"] #abre dicionario de evolution_details para cada espécie
            species = evolution["species"] # pokémon resultante da evolução


            for evolves in evolution_details:

                evolution_fields = {

                    "id":data["id"],
                    "pokemon_id": base_species["url"].split("/")[-2],
                    "pokemon_evolution_id": species["url"].split("/")[-2],
                    "base_form": evolves["base_form"]["name"] if evolves["base_form"] else None,
                    "gender": evolves["gender"]["url"].split("/")[-2] if evolves["gender"] else None,
                    "held_item": evolves["held_item"]["url"].split("/")[-2] if evolves["held_item"] else None,
                    "item": evolves["item"]["url"].split("/")[-2] if evolves["item"] else None,
                    "known_move": evolves["known_move"]["url"].split("/")[-2] if evolves["known_move"] else None,
                    "known_move_type": evolves["known_move_type"]["url"].split("/")[-2] if evolves["known_move_type"] else None,
                    "location": evolves["location"]["url"].split("/")[-2] if evolves["location"] else None,
                    "min_affection": evolves["min_affection"],
                    "min_beauty": evolves["min_beauty"],
                    "min_damage_taken": evolves["min_damage_taken"],
                    "min_happiness": evolves["min_happiness"],
                    "min_level": evolves["min_level"],
                    "min_move_count": evolves["min_move_count"],
                    "min_steps": evolves["min_steps"],
                    "needs_multiplayer": evolves["needs_multiplayer"],
                    "needs_overworld_rain": evolves["needs_overworld_rain"],
                    "time_of_day": evolves["time_of_day"],
                    "trigger": evolves["trigger"]["name"] if evolves["trigger"] else None

                    }

                evolution_chain_list.append(evolution_fields)
    except Exception as e:
        print(f"Faile on file {i}: {e}")
        continue

    df_evolution_chain = pd.DataFrame(evolution_chain_list)
    tb_evolution_chain = df_evolution_chain.set_index("id").sort_values(by="pokemon_id", ascending=True).drop_duplicates()

    print(tb_evolution_chain)

   pokemon_id pokemon_evolution_id base_form gender held_item  item  \
id
1           1                    2      None   None      None  None

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None

   min_damage_taken min_happiness  min_level min_move_count min_steps  \
id
1              None          None         16           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
   pokemon_id pokemon_evolution_id base_form gender held_item  item  \
id
1           1                    2      None   None      None  None
10        172                   25      None   None      None  None

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
10              False                 False              level-up
   pokemon_id pokemon_evolution_id        base_form gender held_item  item  \
id
1           1                    2             None   None      None  None
10        172                   25             None   None      None  None
11         27                   28             None   None      None  None
11         27                   28  sandshrew-alola   None      None   885

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None
11       None            None     None          None       None
11       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None
11             None            NaN       22.0           None      None
11             None            NaN        NaN           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
10              False                 False              level-up
11              False                 False              level-up
11              False                 False              use-item
   pokemon_id pokemon_evolution_id        base_form gender held_item  item  \
id
1           1                    2             None   None      None  None
10        172                   25             None   None      None  None
11         27                   28             None   None      None  None
11         27                   28  sandshrew-alola   None      None   885
12         29                   30             None   None      None  None

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None
11       None            None     None          None       None
11       None            None     None          None       None
12       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None
11             None            NaN       22.0           None      None
11             None            NaN        NaN           None      None
12             None            NaN       16.0           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
10              False                 False              level-up
11              False                 False              level-up
11              False                 False              use-item
12              False                 False              level-up

   pokemon_id pokemon_evolution_id        base_form gender held_item  item  \
id
1           1                    2             None   None      None  None
10        172                   25             None   None      None  None
11         27                   28             None   None      None  None
11         27                   28  sandshrew-alola   None      None   885
12         29                   30             None   None      None  None
13         32                   33             None   None      None  None

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None
11       None            None     None          None       None
11       None            None     None          None       None
12       None            None     None          None       None
13       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None
11             None            NaN       22.0           None      None
11             None            NaN        NaN           None      None
12             None            NaN       16.0           None      None
13             None            NaN       16.0           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
10              False                 False              level-up
11              False                 False              level-up
11              False                 False              use-item
12              False                 False              level-up
13              False                 False              level-up
   pokemon_id pokemon_evolution_id        base_form gender held_item  item  \
id
1           1                    2             None   None      None  None
10        172                   25             None   None      None  None
14        173                   35             None   None      None  None
11         27                   28             None   None      None  None
11         27                   28  sandshrew-alola   None      None   885
12         29                   30             None   None      None  None
13         32                   33             None   None      None  None

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None
14       None            None     None          None       None
11       None            None     None          None       None
11       None            None     None          None       None
12       None            None     None          None       None
13       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None
14             None          160.0        NaN           None      None
11             None            NaN       22.0           None      None
11             None            NaN        NaN           None      None
12             None            NaN       16.0           None      None
13             None            NaN       16.0           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
10              False                 False              level-up
14              False                 False              level-up
11              False                 False              level-up
11              False                 False              use-item
12              False                 False              level-up
13              False                 False              level-up
   pokemon_id pokemon_evolution_id        base_form gender held_item  item  \
id
1           1                    2             None   None      None  None
10        172                   25             None   None      None  None
14        173                   35             None   None      None  None
11         27                   28             None   None      None  None
11         27                   28  sandshrew-alola   None      None   885
12         29                   30             None   None      None  None
13         32                   33             None   None      None  None
15         37                   38             None   None      None    82
15         37                   38     vulpix-alola   None      None   885

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None
14       None            None     None          None       None
11       None            None     None          None       None
11       None            None     None          None       None
12       None            None     None          None       None
13       None            None     None          None       None
15       None            None     None          None       None
15       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None
14             None          160.0        NaN           None      None
11             None            NaN       22.0           None      None
11             None            NaN        NaN           None      None
12             None            NaN       16.0           None      None
13             None            NaN       16.0           None      None
15             None            NaN        NaN           None      None
15             None            NaN        NaN           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
10              False                 False              level-up
14              False                 False              level-up
11              False                 False              level-up
11              False                 False              use-item
12              False                 False              level-up
13              False                 False              level-up
15              False                 False              use-item
15              False                 False              use-item
   pokemon_id pokemon_evolution_id        base_form gender held_item  item  \
id
1           1                    2             None   None      None  None
10        172                   25             None   None      None  None
14        173                   35             None   None      None  None
16        174                   39             None   None      None  None
11         27                   28             None   None      None  None
11         27                   28  sandshrew-alola   None      None   885
12         29                   30             None   None      None  None
13         32                   33             None   None      None  None
15         37                   38             None   None      None    82
15         37                   38     vulpix-alola   None      None   885

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None
14       None            None     None          None       None
16       None            None     None          None       None
11       None            None     None          None       None
11       None            None     None          None       None
12       None            None     None          None       None
13       None            None     None          None       None
15       None            None     None          None       None
15       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None
14             None          160.0        NaN           None      None
16             None          160.0        NaN           None      None
11             None            NaN       22.0           None      None
11             None            NaN        NaN           None      None
12             None            NaN       16.0           None      None
13             None            NaN       16.0           None      None
15             None            NaN        NaN           None      None
15             None            NaN        NaN           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
10              False                 False              level-up
14              False                 False              level-up
16              False                 False              level-up
11              False                 False              level-up
11              False                 False              use-item
12              False                 False              level-up
13              False                 False              level-up
15              False                 False              use-item
15              False                 False              use-item
   pokemon_id pokemon_evolution_id        base_form gender held_item  item  \
id
1           1                    2             None   None      None  None
10        172                   25             None   None      None  None
14        173                   35             None   None      None  None
16        174                   39             None   None      None  None
11         27                   28             None   None      None  None
11         27                   28  sandshrew-alola   None      None   885
12         29                   30             None   None      None  None
13         32                   33             None   None      None  None
15         37                   38             None   None      None    82
15         37                   38     vulpix-alola   None      None   885
17         41                   42             None   None      None  None

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None
14       None            None     None          None       None
16       None            None     None          None       None
11       None            None     None          None       None
11       None            None     None          None       None
12       None            None     None          None       None
13       None            None     None          None       None
15       None            None     None          None       None
15       None            None     None          None       None
17       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None
14             None          160.0        NaN           None      None
16             None          160.0        NaN           None      None
11             None            NaN       22.0           None      None
11             None            NaN        NaN           None      None
12             None            NaN       16.0           None      None
13             None            NaN       16.0           None      None
15             None            NaN        NaN           None      None
15             None            NaN        NaN           None      None
17             None            NaN       22.0           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
10              False                 False              level-up
14              False                 False              level-up
16              False                 False              level-up
11              False                 False              level-up
11              False                 False              use-item
12              False                 False              level-up
13              False                 False              level-up
15              False                 False              use-item
15              False                 False              use-item
17              False                 False              level-up
   pokemon_id pokemon_evolution_id        base_form gender held_item  item  \
id
1           1                    2             None   None      None  None
10        172                   25             None   None      None  None
14        173                   35             None   None      None  None
16        174                   39             None   None      None  None
11         27                   28             None   None      None  None
11         27                   28  sandshrew-alola   None      None   885
12         29                   30             None   None      None  None
13         32                   33             None   None      None  None
15         37                   38             None   None      None    82
15         37                   38     vulpix-alola   None      None   885
17         41                   42             None   None      None  None
18         43                   44             None   None      None  None

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None
14       None            None     None          None       None
16       None            None     None          None       None
11       None            None     None          None       None
11       None            None     None          None       None
12       None            None     None          None       None
13       None            None     None          None       None
15       None            None     None          None       None
15       None            None     None          None       None
17       None            None     None          None       None
18       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None
14             None          160.0        NaN           None      None
16             None          160.0        NaN           None      None
11             None            NaN       22.0           None      None
11             None            NaN        NaN           None      None
12             None            NaN       16.0           None      None
13             None            NaN       16.0           None      None
15             None            NaN        NaN           None      None
15             None            NaN        NaN           None      None
17             None            NaN       22.0           None      None
18             None            NaN       21.0           None      None

    needs_multiplayer  needs_overworld_rain time_of_day   trigger
id
1               False                 False              level-up
10              False                 False              level-up
14              False                 False              level-up
16              False                 False              level-up
11              False                 False              level-up
11              False                 False              use-item
12              False                 False              level-up
13              False                 False              level-up
15              False                 False              use-item
15              False                 False              use-item
17              False                 False              level-up
18              False                 False              level-up
   pokemon_id pokemon_evolution_id        base_form gender held_item  item  \
id
1           1                    2             None   None      None  None
10        172                   25             None   None      None  None
14        173                   35             None   None      None  None
16        174                   39             None   None      None  None
11         27                   28             None   None      None  None
11         27                   28  sandshrew-alola   None      None   885
12         29                   30             None   None      None  None
13         32                   33             None   None      None  None
15         37                   38             None   None      None    82
15         37                   38     vulpix-alola   None      None   885
17         41                   42             None   None      None  None
18         43                   44             None   None      None  None
19         46                   47             None   None      None  None

   known_move known_move_type location min_affection min_beauty  \
id
1        None            None     None          None       None
10       None            None     None          None       None
14       None            None     None          None       None
16       None            None     None          None       None
11       None            None     None          None       None
11       None            None     None          None       None
12       None            None     None          None       None
13       None            None     None          None       None
15       None            None     None          None       None
15       None            None     None          None       None
17       None            None     None          None       None
18       None            None     None          None       None
19       None            None     None          None       None

   min_damage_taken  min_happiness  min_level min_move_count min_steps  \
id
1              None            NaN       16.0           None      None
10             None          220.0        NaN           None      None
14             None          160.0        NaN           None      None
16             None          160.0        NaN           None      None
11             None            NaN       22.0           None      None
11             None            NaN        NaN           None      None
12             None            NaN       16.0           None      None
13             None            NaN       16.0           None      None
15             None            NaN        NaN           None      None
15             None            NaN        NaN           None      None
17             None            NaN       22.0           None      None
18             None            NaN       21.0           None      None
19             None            NaN       24.0           None      None


### tratamento types

#### v2

In [38]:
type_list = []

for file_name in os.listdir(BRONZE_TYPES):

    if not file_name.endswith('.json'):
        continue

    file = load_json(BRONZE_TYPES, file_name)
    try:
        df_type_raw = pd.json_normalize(file)
        df_pokemon_types_raw = pd.json_normalize(file["pokemon"])
        types_cols = df_type_raw[['id', 'name']]
        pokemon_type = df_pokemon_types_raw['pokemon.url'].str.split('/').str[-2]

        df_types = pd.concat([types_cols, pokemon_type], axis=1)
        df_types = df_types.rename(columns={'pokemon.url': 'pokemon_id'})

        type_list.append(df_types)

    except Exception as e:
        print(f"Failed on file {file_name}: {e}")

# Em vez de juntar dois DataFrames de tamanhos diferentes (o que causaria NULLs),
# a gente aproveita que o arquivo JSON já tem o id e o nome do tipo direto na raiz
# (file["id"] e file["name"]). Aí é só adicionar essas informações como colunas novas
# no DataFrame que já tem os pokémons daquele tipo (df_pokemon_types).

# É como se você tivesse uma lista de alunos e precisasse colocar o nome da turma em
# cada linha: em vez de criar outra tabela e tentar juntar, você simplesmente escreve
# o nome da turma em cada linha diretamente.

# No final, a gente extrai o pokemon_id da URL (o número que vem antes da última barra),
# seleciona só as colunas que importam e joga no type_list pra depois concatenar tudo.


df_types["type_id"] = file["id"]
df_types["type_name"] = file["name"]
df_types["pokemon_id"] = df_pokemon_types_raw['pokemon.url'].str.split('/').str[-2]

df_pokemon_types = df_types[["type_id", "type_name", "pokemon_id"]]
type_list.append(df_pokemon_types)

print(df_pokemon_types)

    type_id type_name pokemon_id
0         9     steel         81
1         9     steel         82
2         9     steel        205
3         9     steel        208
4         9     steel        212
..      ...       ...        ...
94        9     steel      10310
95        9     steel      10311
96        9     steel      10316
97        9     steel      10317
98        9     steel      10318

[99 rows x 3 columns]

#### v1

In [39]:
type_list = []

for i in os.listdir(BRONZE_TYPES):

    try:
        data = load_json(BRONZE_TYPES, i)
        pokemon = data["pokemon"]

        for p in pokemon:

            for d in data:

                type_fields = {
                    "id": data["id"],
                    "name": data["name"],
                    "slot": p["slot"],
                    "pokemon_id": p["pokemon"]["url"].split("/")[-2]
            }

            type_list.append(type_fields)

    except Exception as e:
        print(f"Failed on file {i}: {e}")

df_type = pd.DataFrame(type_list)
tb_type = df_type.set_index("id").sort_values(by="id").drop_duplicates()

print(tb_type)

      name  slot pokemon_id
id
1   normal     1        115
1   normal     1        128
1   normal     1        132
1   normal     1        333
1   normal     1        335
..     ...   ...        ...
18   fairy     2      10282
18   fairy     1      10296
18   fairy     2      10317
18   fairy     2      10318
18   fairy     1      10061

[2016 rows x 3 columns]

### [desuso] cria/atualiza e carrega tabelas

In [40]:
# with engine.connect() as conn:

#     conn.execute(
#         text(

#             """CREATE TABLE IF NOT EXISTS db_pokemon.tb_pokemon_species (
#             id INT PRIMARY KEY,
#             name VARCHAR(255) NOT NULL,
#             evolution_chain_id INT NOT NULL,
#             habitat VARCHAR(255),
#             is_baby BOOLEAN ,
#             is_legendary BOOLEAN ,
#             is_mythical BOOLEAN

#             );"""
#         )
#     )

#     conn.execute(
#         text(

#             """CREATE TABLE IF NOT EXISTS db_pokemon.tb_type (

#             id INT PRIMARY KEY,
#             pokemon_id INT NOT NULL,
#             name VARCHAR(255),
#             FOREIGN KEY (pokemon_id) REFERENCES db_pokemon.tb_pokemon_species(id)

#             );"""
#         )
#     )

#     conn.execute(
#         text(

#             """CREATE TABLE IF NOT EXISTS db_pokemon.tb_encounters (

#             id INT,
#             name VARCHAR(255),
#             pokemon_id INT NOT NULL,
#             PRIMARY KEY (id, pokemon_id),
#             FOREIGN KEY (pokemon_id) REFERENCES db_pokemon.tb_pokemon_species(id)

#             );"""
#         )
#     )

#     conn.execute(
#         text(

#             """CREATE TABLE IF NOT EXISTS db_pokemon.tb_evolution_chain (

#             id INT,
#             pokemon_id INT NOT NULL,
#             pokemon_evolution_id INT NOT NULL,
#             base_form VARCHAR(255),
#             gender VARCHAR(255),
#             held_item VARCHAR(255),
#             item  VARCHAR(255),
#             known_move VARCHAR(255),
#             known_move_type VARCHAR(255),
#             location VARCHAR(255),
#             min_affection INT,
#             min_beauty INT,
#             min_damage_taken INT,
#             min_happiness INT,
#             min_level INT,
#             min_move_count INT,
#             min_steps INT,
#             needs_multiplayer BOOLEAN,
#             needs_overworld_rain BOOLEAN,
#             time_of_day VARCHAR(255),
#             `trigger` VARCHAR(255)

#             );"""
#         )
#     )

#     conn.commit()

In [41]:
# df_encounters.to_sql(
#     name="tb_encounters",
#     if_exists="replace",
#     index=False,
#     con=engine)

# df_evolution_chain.to_sql(
#     name="tb_evolution_chain",
#     if_exists="replace",
#     index=False,
#     con=engine)

# df_type.to_sql(
#     name="tb_type",
#     if_exists="replace",
#     index=False,
#     con=engine)

# # fica ao final pq tem foreign key nas outras, então ao atualizar o DROP TABLE nao dá certo
# df_pokemon_species.to_sql(
#     name="tb_pokemon_species",
#     if_exists="replace",
#     index=False,
#     con=engine)

### Cria arquivo parquet

In [42]:
df_encounters.to_parquet(f'{SILVER_INTERMEDIARIA}/df_encounters.parquet', engine='pyarrow')
df_evolution_chain.to_parquet(f'{SILVER_INTERMEDIARIA}/df_evolution_chain.parquet', engine='pyarrow')
df_type.to_parquet(f'{SILVER_INTERMEDIARIA}/df_type.parquet', engine='pyarrow')
df_pokemon_species.to_parquet(f'{SILVER_INTERMEDIARIA}/df_pokemon_species.parquet', engine='pyarrow')